# Generated by Django 4.2.16 on 2024-11-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reservation_status'),
        ('payments', '0004_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation'),
        ),
    ]
