# Generated by Django 4.2.16 on 2024-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0004_alter_reservation_reservation_date'),
        ('gfgauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cuisine',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='Restaurant_handling.cuisine'),
        ),
    ]
