# Generated by Django 4.2.16 on 2024-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0003_alter_business_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_restaurants',
            field=models.ManyToManyField(blank=True, related_name='favourite_users', to='gfgauth.business'),
        ),
    ]
