# Generated by Django 4.2.16 on 2024-10-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0005_customuser_dietery_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dietery_preferences',
            new_name='dietery_preference',
        ),
    ]
