# Generated by Django 4.2.16 on 2024-10-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0006_dieterypreference'),
        ('gfgauth', '0006_rename_dietery_preferences_customuser_dietery_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dietery_preference',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietery_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Restaurant_handling.dieterypreference'),
        ),
    ]
