# Generated by Django 4.2.16 on 2024-10-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0006_dieterypreference'),
        ('gfgauth', '0007_remove_customuser_dietery_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dietery_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietery_preference',
            field=models.ManyToManyField(blank=True, related_name='users', to='Restaurant_handling.dieterypreference'),
        ),
    ]
