# Generated by Django 4.2.16 on 2024-11-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0012_alter_businessnotification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessNotification',
        ),
    ]
