# Generated by Django 4.2.16 on 2024-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0013_delete_businessnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_max_table_size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_time_slot',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
