# Generated by Django 4.2.16 on 2024-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0014_business_business_max_table_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_max_table_size',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_time_slot',
        ),
        migrations.AddField(
            model_name='business',
            name='business_max_table_capacity',
            field=models.IntegerField(default=4),
        ),
    ]
