# Generated by Django 4.2.16 on 2024-12-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0018_alter_business_business_tax_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='business',
            name='opening_time',
        ),
    ]
