# Generated by Django 4.2.16 on 2024-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_description', models.TextField(max_length=100)),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('dish_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
