# Generated by Django 4.2.16 on 2024-10-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gfgauth', '0001_initial'),
        ('Restaurant_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfgauth.business'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cuisine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_handling.cuisine'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_handling.dishtype'),
        ),
    ]
