# Generated by Django 4.2.16 on 2024-10-25 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gfgauth', '0001_initial'),
        ('Restaurant_handling', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('reservation_party_size', models.IntegerField()),
                ('reservation_special_requests', models.TextField(max_length=100)),
                ('reservation_status', models.CharField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfgauth.business')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
