# Generated by Django 4.2.16 on 2024-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
