# Generated by Django 4.2.16 on 2024-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0005_dish_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieteryPreference',
            fields=[
                ('dietery_id', models.AutoField(primary_key=True, serialize=False)),
                ('dietery_name', models.CharField(max_length=100)),
            ],
        ),
    ]
