# Generated by Django 4.2.16 on 2024-10-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0006_dieterypreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_special_requests',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
