# Generated by Django 4.2.16 on 2024-11-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0010_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
