# Generated by Django 4.2.16 on 2024-11-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_handling', '0011_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
    ]
