# Generated by Django 4.2.16 on 2024-11-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfgauth', '0013_delete_businessnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant_handling', '0013_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_rating', models.IntegerField()),
                ('review_text', models.TextField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfgauth.business')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
